export const buyerBookData = [
  {
    "image": 'img/book.png',
    "itemBuyKey": 1,
    "custKey": 101,
    "itemTitle": "책제목1",
    "author": "책저자",
    "publisher": "출판",
    "expiry": 20230301, 
    "aucStatus": 2,
    "damage": '상',
    "price": '11,000',
  },
  {
    "image": 'img/book.png',
    "itemBuyKey": 2,
    "custKey": 102,
    "itemTitle": "책제목2",
    "author": "책저자",
    "publisher": "출판",
    "expiry": 20230228,
    "aucStatus": 1,
    "damage": '상',
    "price": '11,000',
  },
  {
    "image": 'img/book.png',
    "itemBuyKey": 3,
    "custKey": 103,
    "itemTitle": "책제목3",
    "author": "책저자",
    "publisher": "출판",
    "expiry": 20230315,
    "aucStatus": 3,
    "damage": '상',
    "price": '11,000',
  },
    {
    "image": 'img/book.png',
    "itemBuyKey": 1,
    "custKey": 101,
    "itemTitle": "책제목1",
    "author": "책저자",
    "publisher": "출판",
    "expiry": 20230301,
    "aucStatus": 2,
    "damage": '상',
    "price": '11,000',
  },
  {
    "image": 'img/book.png',
    "itemBuyKey": 2,
    "custKey": 102,
    "itemTitle": "책제목2",
    "author": "책저자",
    "publisher": "출판",
    "expiry": 20230228,
    "aucStatus": 1,
    "damage": '상',
    "price": '11,000',
  },
  {
    "image": 'img/book.png',
    "itemBuyKey": 3,
    "custKey": 103,
    "itemTitle": "책제목3",
    "author": "책저자",
    "publisher": "출판",
    "expiry": 20230315,
    "aucStatus": 3,
    "damage": '상',
    "price": '11,000',
  }
]
